spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        ddl-auto: create
    defer-datasource-initialization: true
  flyway:
    enabled: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
