spring:
  datasource:
    url: ${DEV_DATASOURCE_URL}?rewriteBatchedStatements=true
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
