spring:
  session:
    store-type: jdbc
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 5
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs
  cache:
    disabled: true
oauth:
  google:
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    redirectUri: ${REDIRECT_URI}
    grantType: authorization_code
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
      base-path: /manage
info:
    version: '1.2.2'
