INSERT INTO MEDIA_SOURCE(identifier) VALUES('GuguBEvPuCQ');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('z8IIYm-NqQc');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('SOspRSURVjk');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('9-ORcZS43rg');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('3zGolvJu24g');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('i6j_QQkZ7eI');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('NO_vjP-dZAQ');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('oRc9HnLvgtw');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('u9_PSrHxqj0');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('6aU9LXhMp8k');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('WzXPNDxuOS8');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('Y_eX_4-O26w');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('A2f7wOB4mOA');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('QwT4bBnLlq4');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('rhrGnbCC0-0');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('illwwKfv1UY');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('b9Pha_aJrok');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('G5u2ddCtgqY');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('Nfw66Lv-ZjQ');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('4oHk7YPOUXE');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('kVpHx46FKmk');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('P2qg-fipjkQ');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('oN5Te9Ou7W8');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('3rNJKcv2arg');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('PePwZRiABik');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('pNp8_-kkH14');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('yh6H1s5m3rE');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('PGAndAgf-yU');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('bgNgUyqa9iw');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('2Y__DJhV0M0');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('qCoDr3kv_AQ');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('HiQ08btVhts');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('e4j57LsGjls');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('13buYM0QhMs');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('XLDY8gCqg2w');
INSERT INTO MEDIA_SOURCE(identifier) VALUES('devQQvUNrUE');

INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Speak to me', 'Zaumne', 'ROCK', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word"]');
INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Friends', 'Zaumne', 'ROCK', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word"]');
INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Hand in Hand', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word"]');
INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Valis', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken","Drone"]');
INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Monstera deliciosa', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken","Drone"]');
INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Curious in Epidavros', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken","Drone"]');
INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Born Under Punches (The Heat Goes On)', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Born Under Punches 2', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO TRACK(title, artist, super_genre, sub_genres) VALUES ('Born Under Punches 3', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');

INSERT INTO ROOM(media_source_id, track_id) VALUES(1, 1);
INSERT INTO ROOM(media_source_id, track_id) VALUES(2, 2);
INSERT INTO ROOM(media_source_id, track_id) VALUES(3, 3);
INSERT INTO ROOM(media_source_id, track_id) VALUES(4, 4);
INSERT INTO ROOM(media_source_id, track_id) VALUES(5, 5);
INSERT INTO ROOM(media_source_id, track_id) VALUES(6, 6);
INSERT INTO ROOM(media_source_id, track_id) VALUES(7, 7);
INSERT INTO ROOM(media_source_id, track_id) VALUES(8, 8);
INSERT INTO ROOM(media_source_id, track_id) VALUES(9, 9);
