INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Speak to me', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word","ASMR"]');
INSERT INTO media_source(identifier) VALUES ('eAp9FkfoiRQ');
INSERT INTO room(media_source_id, track_id) VALUES ('1','1');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Friends', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word","ASMR"]');
INSERT INTO media_source(identifier) VALUES ('eAp9FkfoiRQ');
INSERT INTO room(media_source_id, track_id) VALUES ('2','2');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Hand in hand', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word","ASMR"]');
INSERT INTO media_source(identifier) VALUES ('eAp9FkfoiRQ');
INSERT INTO room(media_source_id, track_id) VALUES ('3','3');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Special', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word","ASMR"]');
INSERT INTO media_source(identifier) VALUES ('eAp9FkfoiRQ');
INSERT INTO room(media_source_id, track_id) VALUES ('4','4');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('New design', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word","ASMR"]');
INSERT INTO media_source(identifier) VALUES ('eAp9FkfoiRQ');
INSERT INTO room(media_source_id, track_id) VALUES ('5','5');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('MFW tired', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word","ASMR"]');
INSERT INTO media_source(identifier) VALUES ('eAp9FkfoiRQ');
INSERT INTO room(media_source_id, track_id) VALUES ('6','6');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Missin'' M', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word","ASMR"]');
INSERT INTO media_source(identifier) VALUES ('eAp9FkfoiRQ');
INSERT INTO room(media_source_id, track_id) VALUES ('7','7');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Friends (stay put mix)', 'Zaumne', 'SOUNDS_AND_EFFECTS', '["Outsider House","ASMR","Ambient House","Ambient Dub","Spoken Word","ASMR"]');
INSERT INTO media_source(identifier) VALUES ('eAp9FkfoiRQ');
INSERT INTO room(media_source_id, track_id) VALUES ('8','8');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('I''m Following You', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('9','9');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Valis', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('10','10');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Curious in Epidavros', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('11','11');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Adaptation assez facile', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('12','12');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Monstera deliciosa', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('13','13');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Visnaga', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('14','14');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('A House a Dance a Poem', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('15','15');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Vermillions', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('16','16');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Hier le désert', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('17','17');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('No Fear but Anticipation', 'Félicia Atkinson', 'SOUNDS_AND_EFFECTS', '["Electroacoustic","Ambient","ASMR","Spoken Word","Drone"]');
INSERT INTO media_source(identifier) VALUES ('xL0nU_gEqLo');
INSERT INTO room(media_source_id, track_id) VALUES ('18','18');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Pink Moon', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('19','19');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Place to Be', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('20','20');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Road', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('21','21');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Which Will', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('22','22');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Horn', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('23','23');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Things Behind the Sun', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('24','24');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Know', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('25','25');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Parasite', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('26','26');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Free Ride', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('27','27');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Harvest Breed', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('28','28');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('From the Morning', 'Nick Drake', 'FOLK', '["Contemporary Folk","Singer-Songwriter","Folk Baroque"]');
INSERT INTO media_source(identifier) VALUES ('Q2JjJPDz3EE');
INSERT INTO room(media_source_id, track_id) VALUES ('29','29');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The King of Carrot Flowers Pt. One', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('30','30');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The King of Carrot Flowers Pts. Two & Three', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('31','31');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('In the Aeroplane Over the Sea', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('32','32');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Two-Headed Boy', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('33','33');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Fool', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('34','34');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Holland, 1945', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('35','35');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Communist Daughter', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('36','36');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Oh Comely', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('37','37');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Ghost', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('38','38');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('[untitled]', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('39','39');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Two-Headed Boy Pt. Two', 'Neutral Milk Hotel', 'FOLK', '["Indie Folk","Indie Rock","Psychedelic Folk","Singer-Songwriter","Slacker Rock","British Brass Band"]');
INSERT INTO media_source(identifier) VALUES ('jsM7XS-2X50');
INSERT INTO room(media_source_id, track_id) VALUES ('40','40');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Doină', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('41','41');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Wild Silence', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('42','42');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Iag Bari', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('43','43');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Dusty Road', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('44','44');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Lume, lume', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('45','45');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Jocul boldenilor', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('46','46');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Horă din Petroșnița', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('47','47');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Bănățeană', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('48','48');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Tu Romnie', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('49','49');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Moliendo Café', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('50','50');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Balda lui Ioan', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('51','51');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Besh O Drom', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('52','52');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Hora Andalusia', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('53','53');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Hurichestra', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('54','54');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('So te kerau?', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('55','55');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Horă lăutarească', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('56','56');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Gânduri de om bătrân', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('57','57');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Bubamara', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Jazz manouche"]');
INSERT INTO media_source(identifier) VALUES ('LYRlm_oc8mM');
INSERT INTO room(media_source_id, track_id) VALUES ('58','58');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Asfalt tango', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('59','59');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Manuela oh Manuela', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('60','60');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Sîrba de la lași', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('61','61');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Hora de la monăstirea', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('62','62');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Mariana', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('63','63');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Manea cu voce', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('64','64');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Mr. Lobaloba', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('65','65');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Țigănească', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('66','66');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Doină și cîntec', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('67','67');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Hora lui Pusac', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('68','68');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Hai Romale!', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('69','69');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Piece de Tarita', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('70','70');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Lume, lume și hora', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('71','71');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Bălășeanca de 8 ore', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('72','72');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Sîrbă fluierată', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('73','73');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Manea țiganilor', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('74','74');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Casablanca', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('75','75');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Baro Biao (Pașcani Wedding)', 'Fanfare Ciocărlia', 'FOLK', '["Balkan Brass Band","Romani Folk Music","Romanian Folk Music"]');
INSERT INTO media_source(identifier) VALUES ('NX728WXZ9dI');
INSERT INTO room(media_source_id, track_id) VALUES ('76','76');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('[untitled]', 'Aphex Twin', 'AMBIENT', '["Ambient","Electronic","Dark Ambient","Ambient Techno"]');
INSERT INTO media_source(identifier) VALUES ('IXw4RHOd6O0');
INSERT INTO room(media_source_id, track_id) VALUES ('77','77');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Blue Calx', 'Aphex Twin', 'AMBIENT', '["Ambient","Electronic","Dark Ambient","Ambient Techno"]');
INSERT INTO media_source(identifier) VALUES ('IXw4RHOd6O0');
INSERT INTO room(media_source_id, track_id) VALUES ('78','78');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Tape 1', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('79','79');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Daughters of Darkness', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('80','80');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Left for Dead', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('81','81');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Satanic Demona Part I', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('82','82');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Satanic Demona Part II', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('83','83');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Curare', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('84','84');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Carnal Flowers', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('85','85');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Tape 2', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('86','86');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Her Face Is Not Her Real Face', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('87','87');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Body Double', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('88','88');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Slaves for the After Life', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('89','89');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Source', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('90','90');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Tape 3', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('91','91');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Santa Sangre Part I & II', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('92','92');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('A Thousand Demons Invocation', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('93','93');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Tape 4', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('94','94');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Will You Die for Me?', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('95','95');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Black Pastures', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('96','96');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Tape Ø', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('97','97');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Devil''s Fork', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('98','98');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Invisibles', 'Natural Snow Buildings', 'AMBIENT', '["Drone","Free Folk","Ritual Ambient","Noise","Neo-Medieval Folk","Avant-Folk","Tribal Ambient"]');
INSERT INTO media_source(identifier) VALUES ('liE7HwBahb8');
INSERT INTO room(media_source_id, track_id) VALUES ('99','99');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Dead Creek Drawl', 'Old Saw', 'AMBIENT', '["Ambient Americana","American Primitivism","Drone","Free Folk"]');
INSERT INTO media_source(identifier) VALUES ('gwodTQrGTcA');
INSERT INTO room(media_source_id, track_id) VALUES ('100','100');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Mechanical Bull at Our Lady of the Valley', 'Old Saw', 'AMBIENT', '["Ambient Americana","American Primitivism","Drone","Free Folk"]');
INSERT INTO media_source(identifier) VALUES ('gwodTQrGTcA');
INSERT INTO room(media_source_id, track_id) VALUES ('101','101');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Dirtbikes of Heaven, Grains of the Field', 'Old Saw', 'AMBIENT', '["Ambient Americana","American Primitivism","Drone","Free Folk"]');
INSERT INTO media_source(identifier) VALUES ('gwodTQrGTcA');
INSERT INTO room(media_source_id, track_id) VALUES ('102','102');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Chewing the Bridle', 'Old Saw', 'AMBIENT', '["Ambient Americana","American Primitivism","Drone","Free Folk"]');
INSERT INTO media_source(identifier) VALUES ('gwodTQrGTcA');
INSERT INTO room(media_source_id, track_id) VALUES ('103','103');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Last American Hero', 'James Ferraro', 'AMBIENT', '["Hypnagogic Pop","Ambient Americana","New Age","Drone","Post-Minimalism"]');
INSERT INTO media_source(identifier) VALUES ('I5Jsf41tyTk');
INSERT INTO room(media_source_id, track_id) VALUES ('104','104');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Adrenaline''s End', 'James Ferraro', 'AMBIENT', '["Hypnagogic Pop","Ambient Americana","New Age","Drone","Post-Minimalism"]');
INSERT INTO media_source(identifier) VALUES ('I5Jsf41tyTk');
INSERT INTO room(media_source_id, track_id) VALUES ('105','105');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Do I Move You?', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('106','106');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Day and Night', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('107','107');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('In the Dark', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('108','108');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Real Real', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('109','109');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('My Man''s Gone Now', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('110','110');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Backlash Blues', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('111','111');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('I Want a Little Sugar in My Bowl', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('112','112');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Buck', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('113','113');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Since I Fell for You', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('114','114');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The House of the Rising Sun', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('115','115');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Blues for Mama', 'Nina Simone', 'BLUES', '["Soul Blues","Rhythm & Blues"]');
INSERT INTO media_source(identifier) VALUES ('Sg384whVQzc');
INSERT INTO room(media_source_id, track_id) VALUES ('116','116');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Ol'' ''55', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('117','117');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('I Hope That I Don''t Fall in Love With You', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('118','118');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Virginia Avenue', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('119','119');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Old Shoes (& Picture Postcards)', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('120','120');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Midnight Lullaby', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('121','121');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Martha', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('122','122');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Rosie', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('123','123');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Lonely', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('124','124');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Ice Cream Man', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('125','125');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Little Trip to Heaven (On the Wings of Your Love)', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('126','126');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Grapefruit Moon', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('127','127');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Closing Time', 'Tom Waits', 'BLUES', '["Singer-Songwriter","Piano Blues","Jazz","Blues","Vocal Jazz"]');
INSERT INTO media_source(identifier) VALUES ('BeeK37wrBDQ');
INSERT INTO room(media_source_id, track_id) VALUES ('128','128');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Hard Time Killing Floor', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('129','129');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Crawlin'' Kingsnake', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('130','130');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Lucy Mae Blues', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('131','131');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Can''t See Baby', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('132','132');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('I Love the Life I Live', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('133','133');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Louise McGhee', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('134','134');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Moanin'' and Groanin''', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('135','135');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Black Cat Blues', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('136','136');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Bad Life Blues', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('137','137');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Sally Mae', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('138','138');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Anna Lee', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('139','139');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Lonesome Home Blues', 'Buddy Guy', 'BLUES', '["Acoustic Chicago Blues","Delta Blues"]');
INSERT INTO media_source(identifier) VALUES ('PZKtfEMPrh0');
INSERT INTO room(media_source_id, track_id) VALUES ('140','140');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Backwater Blues', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('141','141');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('This Train', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('142','142');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('I Don''t Want No Woman (To Try to Be My Boss)', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('143','143');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Martha', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('144','144');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Tell Me Who', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('145','145');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Bill Bailey', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('146','146');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Alberta', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('147','147');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Goin'' Down This Road', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('148','148');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Tell Me What Kind of Man Jesus Is', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('149','149');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('John Henry', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('150','150');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Glory of Love', 'Big Bill Broonzy', 'BLUES', '["Country Blues","Acoustic Chicago Blues","Spirituals","Traditional Black Gospel"]');
INSERT INTO media_source(identifier) VALUES ('lOaGz44rmB0');
INSERT INTO room(media_source_id, track_id) VALUES ('151','151');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Corpus Christi Side', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('152','152');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('¼ Dead', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('153','153');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Blissful Myth', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('154','154');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Psycho Squat', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('155','155');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Rotten to the Core', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('156','156');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Poppycock', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('157','157');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Cosmic Hearse', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('158','158');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Cloud Song', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('159','159');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Vampire State Building', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('160','160');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Blasphemy Squad', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('161','161');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('When You Are a Martian Church', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('162','162');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Pig in a Blanket', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('163','163');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Rudimental Human Side', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('164','164');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Inside', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('165','165');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Nothing but a Nightmare', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('166','166');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Flesh Crucifix', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('167','167');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Slimy Member', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('168','168');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Love Is Not', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('169','169');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Radio Schizo', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('170','170');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Happy Farm', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('171','171');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Alice Crucifies the Paedophiles', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('172','172');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Army of Jesus', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('173','173');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Dutchmen', 'Rudimentary Peni', 'PUNK', '["Anarcho-Punk","Deathrock","Hardcore Punk","Deathrock"]');
INSERT INTO media_source(identifier) VALUES ('gHdXTLJr8T4');
INSERT INTO room(media_source_id, track_id) VALUES ('174','174');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('[untitled]', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('175','175');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Forget', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('176','176');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Waste of Breath', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('177','177');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Where''s the Freedom?', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('178','178');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Reality Is Waiting for a Bus', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('179','179');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Us Fish Must Swim Together', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('180','180');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Wake Up Screaming', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('181','181');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Adversity', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('182','182');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Rain', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('183','183');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('From the Cradle to the Grave', 'Subhumans', 'PUNK', '["Anarcho-Punk","Art Punk","Post-Punk","Hardcore Punk"]');
INSERT INTO media_source(identifier) VALUES ('8psFxJ8LshE');
INSERT INTO room(media_source_id, track_id) VALUES ('184','184');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Plainsong', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('185','185');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Pictures of You', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('186','186');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Closedown', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('187','187');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Lovesong', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('188','188');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Lullaby', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('189','189');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Fascination Street', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('190','190');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Prayers for Rain', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('191','191');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Same Deep Water as You', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('192','192');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Disintegration', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('193','193');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Untitled', 'The Cure', 'PUNK', '["Gothic Rock","Post-Punk","Dream Pop"]');
INSERT INTO media_source(identifier) VALUES ('ijxk-fgcg7c');
INSERT INTO room(media_source_id, track_id) VALUES ('194','194');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Born Under Punches (The Heat Goes On)', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO media_source(identifier) VALUES ('RjWej8fOdR8');
INSERT INTO room(media_source_id, track_id) VALUES ('195','195');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Crosseyed and Painless', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO media_source(identifier) VALUES ('RjWej8fOdR8');
INSERT INTO room(media_source_id, track_id) VALUES ('196','196');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Great Curve', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO media_source(identifier) VALUES ('RjWej8fOdR8');
INSERT INTO room(media_source_id, track_id) VALUES ('197','197');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Once in a Lifetime', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO media_source(identifier) VALUES ('RjWej8fOdR8');
INSERT INTO room(media_source_id, track_id) VALUES ('198','198');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Houses in Motion', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO media_source(identifier) VALUES ('RjWej8fOdR8');
INSERT INTO room(media_source_id, track_id) VALUES ('199','199');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Seen and Not Seen', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO media_source(identifier) VALUES ('RjWej8fOdR8');
INSERT INTO room(media_source_id, track_id) VALUES ('200','200');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Listening Wind', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO media_source(identifier) VALUES ('RjWej8fOdR8');
INSERT INTO room(media_source_id, track_id) VALUES ('201','201');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Overload', 'Talking Heads', 'PUNK', '["New Wave","Post-Punk","Funk","Afrobeat","Experimental Rock","Dance-Punk"]');
INSERT INTO media_source(identifier) VALUES ('RjWej8fOdR8');
INSERT INTO room(media_source_id, track_id) VALUES ('202','202');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('The Last Bell I Will Ever Hear', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('203','203');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('(I Must Be a Proctologist Because...) All I Do Is Deal W/ Assholes', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('204','204');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('So Lets Go! Nowhere', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('205','205');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Kill the President', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('206','206');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('People Pops & Fudgesicles for the (S)Hit Factory', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('207','207');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Rocketrocketrocketship', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('208','208');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('1-800-ALARM-ME', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('209','209');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('I''ve Got Enemies in High Places', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('210','210');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Disappointment at the Taco Bell', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('211','211');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Piss Off', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('212','212');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Have Fun Rotting by Yourself', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('213','213');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('"Yeah, I Don''t Know What It''s Like to Be Around a Bunch of Hipsters"', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('214','214');
INSERT INTO track(title, artist, super_genre, sub_genres) VALUES ('Last on My List.', 'The Arrogant Sons of Bitches', 'SKA', '["Ska Punk","Skate Punk","Pop Punk","Hardcore Punk","Skacore","Emo","Post-Hardcore"]');
INSERT INTO media_source(identifier) VALUES ('G9oJBatX0pk');
INSERT INTO room(media_source_id, track_id) VALUES ('215','215');
