name: Android CI

on:
  pull_request:
    branches: [ "android" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Create config.properties
      run: |
        cd android && echo "server.url=\"https://ec2-43-200-158-138.ap-northeast-2.compute.amazonaws.com/\"" > config.properties
    
    - name: Init with Gradle
      run: ./android/gradlew init

    - name: Build with Gradle
      run: ./android/gradlew build
      
    - name: Run ktlint
      working-directory: ./android
      run: ./gradlew ktlintCheck
