name: Development CD

on:
  workflow_dispatch:
  push:
    branches: [ "backend" ]
permissions:
  contents: read
jobs:
  deploy:
    runs-on: development
    steps:
      - uses: actions/checkout@v3
      - name: gradle bootjar
        working-directory: ./backend
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar

      - name: kill previous process
        shell: bash {0}
        run: |
          JAR_NAME="DigginRoom-0.0.1-SNAPSHOT.jar"
          PROCESS_ID=$(pgrep -f "$JAR_NAME")
          if [ -n "$PROCESS_ID" ]; then
            sudo kill -9 $PROCESS_ID
            echo "구동중인 애플리케이션을 종료했습니다. (pid : $PROCESS_ID)\n"
          fi

      - name: copy jar
        working-directory: ./backend
        shell: bash {0}
        run: |
          mkdir -p /home/ubuntu/backend
          cp -f build/libs/DigginRoom-0.0.1-SNAPSHOT.jar /home/ubuntu/backend/

      - name: deploy
        working-directory: /home/ubuntu/backend/
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          nohup java -jar \
          -Dspring.profiles.active=develop \
          -DDEV_DATASOURCE_URL=${{ secrets.DEV_DATASOURCE_URL }} \
          -DDEV_DATASOURCE_USERNAME=${{ secrets.DEV_DATASOURCE_USERNAME }} \
          -DDEV_DATASOURCE_PASSWORD=${{ secrets.DEV_DATASOURCE_PASSWORD }} \
          DigginRoom-0.0.1-SNAPSHOT.jar &
