name: Java CD

on:
  workflow_dispatch:
  push:
permissions:
  contents: read
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: gradle bootjar
        working-directory: ./backend
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar
        
      - name: deploy
        working-directory: ./backend
        run: |
          sudo java -jar build/libs/DigginRoom-0.0.1-SNAPSHOT.jar &
