name: Android CI

on:
  pull_request:
    branches: [ "android" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create config.properties
      working-directory: ./android
      run: |
        touch config.properties
        echo "server.url=\"secret\"" >> config.properties
        echo "server.clientId=\"secret\"" >> config.properties
        echo "server.clientSecret=\"secret\"" >> config.properties
        echo "kakao.nativeKey=\"secret\"" >> config.properties

    - name: Create google-services.json
      working-directory: ./android/app
      run: |
        touch google-services.json
        echo "${{ secrets.ANDROID_GOOGLE_SERVICES }}" >> google-services.json

    - name: Run test
      working-directory: ./android
      run: ./gradlew test
      
    - name: Run ktlint
      working-directory: ./android
      run: ./gradlew ktlintCheck