name: Java CI with Gradle

on:
  workflow_dispatch:
  pull_request:
    branches: ["backend"]

permissions:
  contents: read

jobs:
  build:
    runs-on: production
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Create dev.conf
      run: |
        echo "flyway.url=${{ secrets.DEV_DATASOURCE_URL }}" > dev.conf
        echo "flyway.user=${{ secrets.DEV_DATASOURCE_USERNAME }}" >> dev.conf
        echo "flyway.password=${{ secrets.DEV_DATASOURCE_PASSWORD }}" >> dev.conf
        echo "flyway.encoding=UTF-8" >> dev.conf
        echo "flyway.outOfOrder=true" >> dev.conf
        echo "flyway.validateOnMigrate=true" >> dev.conf
        echo "flyway.baselineVersion=0" >> dev.conf
      working-directory: ./backend

    - name: flywayValidate
      run: ./gradlew -Dflyway.configFiles=dev.conf flywayValidate --stacktrace
      working-directory: ./backend

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./backend
