name: Java CI with Gradle

on:
  pull_request:
    branches: ["backend"]

permissions:
  contents: read

jobs:
  build:
    runs-on: jolla-palla
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
      
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./backend
